apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mobile-api
  name: stubby-mobile-api-deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: stubby-mobile-api
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: stubby-mobile-api
    spec:
      containers:
        - image: azagniotov/stubby4j:latest-jre11
          imagePullPolicy: Always
          name: stubby-mobile-api
          ports:
            - containerPort: 8884
          env:
           - name: STUBS_PORT
             value: 8884
           - name: YAML_CONFIG
             value: service.yaml 
           - name: WITH_ARGS
             value: --enable_tls_with_alpn_and_http_2 --debug --watch 
          volumeMounts:
            - name: stubby-mobile-api-configmap-volume
              mountPath: /
      volumes:
        - name: stubby-mobile-api-configmap-volume
          configMap:
            name: stubby-mobile-api-configmap
---
apiVersion: v1
kind: Service
metadata:
  namespace: mobile-api
  name: stubby-mobile-api-service
spec:
  ports:
    - port: 8884
      targetPort: 8884
      nodePort: 30301
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: stubby-mobile-api
