version: '3.5'
services:
  stubby4j-jre11:
    image: azagniotov/stubby4j:latest-jre11
    volumes:
      - "./:/home/stubby4j/data"
    container_name: stubby4j
    ports:
      - 8884:8884
      - 8891:8891
      - 7445:7445
    environment:
      YAML_CONFIG: service.yaml
      STUBS_PORT: 8884
      ADMIN_PORT: 8891
      STUBS_TLS_PORT: 7445
      WITH_ARGS: "--enable_tls_with_alpn_and_http_2 --debug --watch"
